#!/usr/bin/env python

import os
import sys

if __name__ == "__main__":
    try:
        os.popen("iconv -f iso8859-9 -t utf-8 '%s' > /tmp/x" % sys.argv[1])
        os.rename("/tmp/x", sys.argv[1])
        print "Subtitle fixed: " + sys.argv[1]
    except IndexError:
        print "Usage: %s FILE" % os.path.basename(sys.argv[0])

