#!/bin/bash

echo $1 | grep '\.secure$' > /dev/null
if [[ $? != 0 ]]
then # secure file with openssl/blowfish
    openssl bf -a -in $1 > $1.tmp && mv $1.tmp $1.secure || rm $1.tmp
else
    UNSECURE_FILE=$(echo $1 | sed s/'\.secure$'//g)
    openssl bf -d -a -in $1 > $1.tmp  && mv $1.tmp $UNSECURE_FILE || rm $1.tmp
fi
